### ISSUE TITLE
Can't find the optimized file

### ISSUE THREAD

**Issue by jeromebg** [graphdeco-inria/reduced-3dgs#14]
Hi, sorry if my question is stupid and I may not have understood how it works...
When trying to reduce a ply file I use the command as described in the doc :
`(gaussian_splatting) C:\Users\jerom\reduced-3dgs>python update_old_ply_format.py -p D:\GAUSSIAN_SPALTTING\cuisine\d800_14mm_300.ply -n d800_14mm_optimized.ply
Not compliant with new format
Begin conversion
Done`
but no new file with new name is generated ?
What am I missing ?
Many thanks

**Comment by PanagiotisP** [comment]
Hello.
Hm, interesting. It should be in the same folder, so `d:\gaussian_splatting\cuisine`. Maybe I've messed up something.
Can you please try to run the script with a debugger and check this line https://github.com/graphdeco-inria/reduced-3dgs/blob/13e7393af8ecd83d69197dec7e4c891b333a7c1c/update_old_ply_format.py#L117C34-L117C38

**Comment by jeromebg** [comment]
Oups my bad, found the file...
And it's indeed much smaller !
Maybe I didn't get something, but the reduced ply file can't be opened in SuperSplat for exemple, I have this message : Cannot read propreties of undefined (reading 'count')
Is it normal ?

**Comment by PanagiotisP** [comment]
Yeah, because the ply format is completely different, so the old loader, in any piece of software, won't work.
Basically, we're now storing x point clouds (with x being the number of SH bands) within a single ply file instead of 1. Also, for the quantised version, we also store the information that is necessary to do the decompression, which, again, deviates a lot from the original ply format.

Going back to the old format shouldn't be that difficult to do (something like loading everything with the new loader and saving it with the old one). Yet, we didn't include it in the repo, as it kinda defeats the purpose
